config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :reviews
  resources :items do
    resources :reviews
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# get '/' => 'items#index'
  root :to => 'home#index'
  get 'items/new' => 'items#new'
  get 'messages' => 'items#show_messages'
  get 'manage_items' => 'items#manage_items'


  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

   resources :items do
    resources :bookings, only: [:create, :show, :update, :edit]
   end

   resources :charges

end

app/models/profile.rb
class Profile < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  belongs_to :user, optional: true

  validates :address, presence: true
  validates :post_code, presence: true


  geocoded_by :address
  after_validation :geocode

def full_address
  "#{address}, #{city}, #{state}, #{post_code}, Australia"
end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    user_id = @profile.user_id
    @my_items = Item.where(user_id: user_id)

    my_likes = Like.where(user_id: user_id)
    puts my_likes.inspect
    item_array = my_likes.pluck(:item_id)
    puts item_array.inspect
    @my_liked_items = Item.where(id: [item_array])
    puts @my_liked_items.inspect
  end

  # GET /profiles/new
  def new
    @profile = Profile.new

  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user


    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile.user = current_user

    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :image, :address, :city, :state, :post_code, :longitude, :latitude, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
<% if profile.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

  <ul>
    <% profile.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-8 col-xl-6">

        <div class="row align-items-center">
          <div class="col mt-4">
            <label>First Name</label>
            <%= form.text_field :first_name, id: :profile_first_name, :class => "form-control", :placeholder => "First Name" %>
          </div>
        </div>

        <div class="row align-items-center">
          <div class="col mt-4">
            <label>Last Name</label>
            <%= form.text_field :last_name, id: :profile_last_name, :class => "form-control", :placeholder => "Last Name" %>
          </div>
        </div>


        <div class="row align-items-center">
          <div class="col mt-4">
            <label>Street</label>
            <%= form.text_field :address, id: :profile_address, :class => "form-control", :placeholder => "Street"  %>
          </div>
        </div>

        <div class="row align-items-center">
          <div class="col mt-4">
            <label>City</label>
            <%= form.text_field :city, id: :profile_city, :class => "form-control", :placeholder => "City" %>
          </div>
        </div>

        <div class="row align-items-center">
          <div class="col mt-4">
            <label>State</label>
            <%= form.text_field :state, id: :profile_state, :class => "form-control", :placeholder => "State" %>
          </div>
        </div>

        <div class="row align-items-center">
          <div class="col mt-4">
            <label>Post-code</label>
            <%= form.number_field :post_code, id: :profile_post_code, :class => "form-control", :placeholder => "Post-code" %>
          </div>
        </div>

        <div class="row align-items-center">
            <div class="col mt-4 img-circle">
              <label> Choose Image</label>
              <%= form.file_field :image, id: :profile_image %>
            </div>
          </div>

        <div class="field">
          <%= form.hidden_field :longitude, id: :profile_longitude %>
        </div>

        <div class="field">
          <%= form.hidden_field :latitude, id: :profile_latitude %>
        </div>

        <div class="row mt-4">
            <div class="col">
              <button class="btn">Submit</button>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Image data</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Post code</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= <img src="<%= profile.image_url %>" height="100" width="100"></img> %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.address %></td>
        <td><%= profile.city %></td>
        <td><%= profile.state %></td>
        <td><%= profile.post_code %></td>
        <td><%= profile.longitude %></td>
        <td><%= profile.latitude %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row justify-content-around mt-5">
    <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12">
      <img src="<%= @profile.image_url %>" height="200" width="200">



    </div>
    <div class="col-lg-9 col-md-4 col-sm-12 col-xs-12">
      <div class="greeting">
        Hey, I’m <%= @profile.first_name %>
      </div>
      <i class="fa fa-map-marker" aria-hidden="true"></i>
      <%= @profile.city %>,
      <%= @profile.state %>
      <p class="mt-3">Dès l’âge de 7 ans, mes parents m’ont certainement offert le plus beau cadeau …Une machine à coudre (pour enfant) ! Le rêve : partager la même passion que ma maman …Mon mentor.</p>
    </div>
  </div>

  <div class="row profile-heading mt-5">
    <h4>My posts<h4><i class="ml-2 fa fa-tags" aria-hidden="true"></i>
  </div>
  <div class="row mt-5">

    <% @my_items.each do |item| %>
    <div class="col-lg 3 col-md-3 col-sm-12 col-xs-12">
      <div class="card mb-5">
        <%= link_to item_path(item) do %>
        <%= image_tag item.image_url , class: "card-img-top img-fluid"%>
        <% end %>
        <div class="card-block">
          <p class="text-h4"><%= item.name %></p>
          <p class="text-h4 text-primary"> $ <%= item.price %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>


  <div class="row profile-heading mt-5">
    <h4>My Likes<h4><i class="ml-2 fa fa-heart" aria-hidden="true"></i>
  </div>
  <div class="row mt-5">

    <% @my_liked_items.each do |item| %>
    <div class="col-lg 3 col-md-3 col-sm-12 col-xs-12">
      <div class="card mb-5">
        <%= link_to item_path(item) do %>
        <%= image_tag item.image_url , class: "card-img-top img-fluid"%>
        <% end %>
        <div class="card-block">
          <p class="text-h4"><%= item.name %></p>
          <p class="text-h4 text-primary"> $ <%= item.price %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row profile-heading mt-5 mb-2">
    <i class="fa fa-map-marker fa-2x mr-2" aria-hidden="true"></i><h4>Location<h4>
  </div>

  <iframe width="800"
    height="450" src = "https://maps.google.com/maps?q=<%= @profile.latitude %>,<%= @profile.longitude %>&hl=es;z=14&amp;output=embed"></iframe>


</div>

























<!-- <iframe width="800"
  height="450" src = "https://maps.google.com/maps?q=<%= @profile.latitude %>,<%= @profile.longitude %>&hl=es;z=14&amp;output=embed"></iframe> -->

<!-- Google Map -->

		<!-- <div class="row">
			<div class="col-md-12">
				<div id="map">

				</div>
				<style>
					#map{
						width: 100%;
						height: 400px;
					}
				</style>
				<script src="https://maps.googleapis.com/maps/api/js"></script>
			    <script> -->
		<!-- // 	      function initialize() {
		// 	        var mapCanvas = document.getElementById('map');
		// 	        var mapOptions = {
		// 	          center: new google.maps.LatLng(<%= @profile.latitude %>, <%= @profile.longitude %>),
		// 	          zoom: 14,
		// 	          mapTypeId: google.maps.MapTypeId.ROADMAP
		// 	        }
		// 	        var map = new google.maps.Map(mapCanvas, mapOptions);
		// 	        var marker = new google.maps.Marker({
		// 	        	position: new google.maps.LatLng(<%= @profile.latitude %>, <%= @profile.longitude %>),
		// 	        	title: "Airbnb Clone"
		// 	        });
		// 	        marker.setMap(map);
		// 	      }
		// 	      google.maps.event.addDomListener(window, 'load', initialize);
		// 	    </script>
    //  -->
		<!-- // 	</div>
		// </div> -->






<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>