config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :reviews
  resources :items do
    resources :reviews
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# get '/' => 'items#index'
  root :to => 'home#index'
  get 'items/new' => 'items#new'
  get 'messages' => 'items#show_messages'
  get 'manage_items' => 'items#manage_items'


  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

   resources :items do
    resources :bookings, only: [:create, :show, :update, :edit]
   end

   resources :charges

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json

  # def preload
  #   room = Item.find(params[:item_id])
  #   today = Date.today
  #   bookings = room.booking.where("start_date >= ? OR end_date >= ?", today, today)
  #
  #   render json: bookings
  # end

  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    if !@booking.present?
      @booking = @item.bookings.new
    end
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
    @item = Item.find(params[:item_id])
    @booking = @item.bookings.find params[:id]

    @booking.user = current_user
  end

  # POST /bookings
  # POST /bookings.json
  def create
    puts "------params create #{params.inspect}"
    # @booking = current_user.bookings.create(booking_params)
    # redirect_to @booking.item, notice: "Your booking has been created..."
    @item = Item.find(params[:item_id])
    @booking = @item.bookings.build(booking_params)

    @booking.user = current_user

    if params[:commit] == 'Book'
      puts @booking.start_date.strftime("%Y-%m-%d").inspect
      @start_date = @booking.start_date.strftime("%Y-%m-%d")
      @end_date = @booking.end_date.strftime("%Y-%m-%d")

      found = false
      @all_bookings = Booking.all

      @all_bookings.each do |booking|
        if booking.has_paid == TRUE
          start_date= booking.start_date.strftime("%Y-%m-%d")
          end_date = booking.end_date.strftime("%Y-%m-%d")
          if @start_date.between?(start_date, end_date) || @end_date.between?(start_date, end_date)
            if booking.item_id == @booking.item_id
              found = true
            end
          end
        end
      end

      if found == true
        redirect_to request.referrer, notice: "This dress is already booked for this period."
      else
        @booking.save!
        redirect_to edit_item_booking_url(@item,@booking), notice: "You have booked the dress successfully. Please contact owner to fix a time for trial or directly proceed with payment."
      end
    end

    if params[:commit] == 'Pay'
      respond_to do |format|
        if @booking.save && params[:commit] == 'Pay'
          format.html { redirect_to item_booking_url(@item,@booking), notice: 'Invoice' }
          format.json { render :show, status: :created, location: @booking }
          # f.json { render action: 'show', status: :created, location: @step }
        else
          format.html { render action: 'new' }
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end

      end
    end

  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    puts "------params update #{params.inspect}"
    @item = Item.find(params[:item_id])

    @booking.user = current_user

    respond_to do |format|
      if @booking.update(booking_params)
        @booking.has_paid = TRUE
        @booking.save()
        format.html { redirect_to item_booking_url(@item,@booking), notice: 'Invoice' }
        format.json { render :show, status: :created, location: @booking }
        # f.json { render action: 'show', status: :created, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
    @item = Item.find(params[:item_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def booking_params
    params.require(:booking).permit(:user_id, :item_id, :start_date, :end_date, :has_paid, :amount)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for([@item, @booking]) do |f| %>

	<!-- <div class="row">
		<div class="col-md-6">
			<label>Check In</label>
			<%#= f.text_field :start_date, placeholder: 'Start Date', class: 'form-control', readonly: 'true' %>
		</div>
		<div class="col-md-6">
			<label>Check Out</label>
			<%#= f.text_field :end_date, placeholder: 'End Date', class: 'form-control', disabled: 'true', readonly: 'true'  %>
		</div>
	</div> -->
<%= f.hidden_field :start_date, data:{ provide:'datepicker' } %>
<%= f.hidden_field :end_date, data:{ provide:'datepicker' } %>
<% if @temp != TRUE %>
	<br>
	 <%= f.label :From %>
	 <%= f.date_field :start_date, data:{ provide:'datepicker' } %>
	 <br>
	 <%= f.label :To %>
	<%= f.date_field :end_date, data:{ provide:'datepicker' } %>

	<br>

	<%= f.hidden_field :item_id, value: @item.id %>
	<%= f.hidden_field :amount, value: @item.price %>

	<div id="preview" style = "display:none;">
		<h4><span id="message"></span></h4>
		<table class = "reservation-table">
			<tbody>
				<tr>
					<td>Day(s)</td>
					<td><span id="reservation_days"></span></td>
				</tr>
			</tbody>
		</table>
	</div>

	<br/>
	<% end %>
	<%# if @item.bookings != NIL %>
	<%#= @item.bookings.where(id: NIL).inspect %>
	<%# if @item.bookings.where(user_id: current_user.id) != NIL %>
	<% if @temp == TRUE %>

		<%= f.submit "Proceed to payment", class: "btn btn-info" %>
		<%= f.submit "Cancel Booking", class: "btn btn-info" %>

	<% else %>
		<%= f.submit "Book", class: "btn btn-info" %>
	<% end %>
	<br>
	<br>
<hr>

	<%# else %>

	<%# end %>
<% end %>

<!-- <script type="text/javascript">
 	$(function(){
 		$('#booking_start_date').datepicker({
 			dateFormat: 'dd-mm-yy'
 		});

 		$('#booking_end_date').datepicker({
 			dateFormat: 'dd-mm-yy'
 		});
 	});
 </script>

<script>
	function unavailable(date) {
		dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
		return [$.inArray(dmy, unavailableDates) == -1];
	}
	$(function() {
		unavailableDates = [];
		$.ajax({
			url: '/preload',
			data: {'item_id': <%= @item.id %>},
			dataType: 'json',
			success: function(data) {
				$.each(data, function(arrID, arrValue) {
					for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
						console.log(d);
						unavailableDates.push($.datepicker.formatDate('dd-mm-yy', d));
					};
				});
				console.log(unavailableDates);
				$('#booking_start_date').datepicker({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#booking_end_date').datepicker("option", "minDate", selected);
						$('#booking_end_date').attr('disabled', false);
					}
				});
				$('#booking_end_date').datepicker({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#booking_start_date').datepicker("option", "maxDate", selected);
					}
				});
			}
		});

	});
</script> -->

app/views/bookings/edit.html.erb
<div class="container">
  <p id="notice">You have booked the dress successfully. Please contact owner to fix a time for trial or directly proceed with payment</p>
  <% @temp = TRUE %>
  <%= render 'form', booking: @booking %>
</div>
<%# @booking.has_paid = TRUE %>
<%# @booking.save() %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Item</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user %></td>
        <td><%= booking.item %></td>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<% if @booking.has_paid == TRUE %>
  <p>
    <strong>Name:</strong>
    <%= @booking.user.profile.first_name %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= @booking.item.name %>
  </p>

  <p>
    <strong>Booked from :</strong>
    <%= @booking.start_date.strftime("%Y-%m-%d") %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= @booking.end_date.strftime("%Y-%m-%d") %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= @booking.amount %>
  </p>


      <%= form_tag charges_path do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
            <label class="amount">
              <span></span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description= <%= @booking.item %>
                  data-amount = <%= @booking.amount * 100 %>
                  data-locale="auto"></script>
      <% end %>
<% else %>

  <div class="btn btn-info">
  <%= link_to 'Make Payment', edit_item_booking_path(@item,@booking) %>
</div>
<% end %>
<%#= link_to 'Edit', edit_booking_path(@booking) %>
<%#= link_to 'Back', bookings_path %>
</div>