config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :reviews
  resources :items do
    resources :reviews
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# get '/' => 'items#index'
  root :to => 'home#index'
  get 'items/new' => 'items#new'
  get 'messages' => 'items#show_messages'
  get 'manage_items' => 'items#manage_items'


  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

   resources :items do
    resources :bookings, only: [:create, :show, :update, :edit]
   end

   resources :charges

end

app/models/item.rb
class Item < ActiveRecord::Base
  include ImageUploader::Attachment.new(:image)
  belongs_to :user
  has_many :reviews
  has_and_belongs_to_many :likers, class_name: 'User', join_table: :likes
  has_many :bookings
  # group_photo.liked_by?(jo)
  def liked_by?(user)
    likers.exists?(user.id)
  end

  def toggle_liked_by(user)
    # If photo has been liked by `user`
    if likers.exists?(user.id)
      likers.destroy(user.id)
    # If photo has *not* been liked by `user`
    else
      likers << user
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :update, :destroy, :show_messages]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    puts "--- inde index with params: #{params.inspect}"
    if params[:category].present?
      @items = Item.where(category: params[:category])
    elsif params[:search]
       @items = Item.search(params[:search]).order("created_at DESC")

    else
      @items = Item.all
    end

    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages).find(session[:conversations])

    @search = Item.search(params[:q])
    @items = @search.result

  #   s3 = Aws::S3::Resource.new(region: 'us-east-1')
  #  @bucket = s3.bucket('sakshi-bucket')

  end

  def show_messages
    @items = Item.all

    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages).find(session[:conversations])
  end



  def manage_items
    @my_items = Item.where(user_id: current_user.id)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    if !@booking.present?
      @booking = @item.bookings.new
    end
    @reviews = @item.reviews.includes(:user).all
    @review  = @item.reviews.build(user_id: current_user.id) if current_user
    @review.user = current_user
    @review.user_id = current_user.id
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @item.user_id = current_user.id
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item.user = current_user
    @item.user_id = current_user.id
    respond_to do |format|
       if is_liking?
         # Toggle whether this photo is liked by the current user
         @item.toggle_liked_by(current_user)
         format.html { redirect_to @item }
         format.json { render :show, status: :ok, location: @item }
       elsif @item.update(item_params)
         format.html { redirect_to @item, notice: 'Item was successfully updated.' }
         format.json { render :show, status: :ok, location: @item }
       else
         format.html { render :edit }
         format.json { render json: @item.errors, status: :unprocessable_entity }
       end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :category, :image, :user_id)
    end

    def is_liking?
       # Is there a `liked` field in the form?
      params.require(:item)[:liked].present?
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
<% if item.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

  <ul>
    <% item.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-8 col-xl-6">
        <div class="row align-items-center">
          <div class="col mt-4">
            <label>Dress name</label>
            <%= form.text_field :name, id: :item_name, :class => "form-control", :placeholder => "Dress Name" %>
          </div>
        </div>

        <div class="row align-items-center">
          <div class="col mt-4">
            <label>Rental price</label>
            <%= form.text_field :price, id: :item_name, :class => "form-control", :placeholder => "Price" %>
          </div>
        </div>
        <div class="row align-items-center">
          <div class="col mt-4">
            <label>Description</label>
            <%= form.text_field :description, id: :item_description, :class => "form-control", :placeholder => "Description" %>
          </div>
        </div>
        <div class="row align-items-center">
          <div class="col mt-4">
            <label>Category</label>
            <%#= form.text_field :category, id: :item_category, :class => "form-control", :placeholder => "Category" %>
            <%= form.select :category, StaticData::Constants::DRESS_CATEGORIES, :class => "form-control", :placeholder => "Description" %>
          </div>
        </div>


          <div class="row align-items-center mt-4">
            <div class="col">
              <label>Upload Image</label>
              <%= form.file_field :image, id: :item_image%>
            </div>
          </div>


                    <div class="field">
                      <%= form.hidden_field :user_id, id: :item_user_id %>
                    </div>

          <div class="row mt-4">
            <div class="col">
              <button class="btn">Submit</button>
            </div>
          </div>


          <% end %>
        </div>
      </div>
    </div>
  </section>

app/views/items/edit.html.erb
<%= render 'form', item: @item %>

  <%#= link_to 'Show', @item %>

<div class=" btn btn-default back-button  col-1">
  <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="">
    <% content_for :search do %>
    <form class="form-inline mt-5 ml-5">
      <%= search_form_for @search do |f| %>

        <div class="col-1.5 ml-5 form-style">
          <%#= f.select :price_gteq, [0,10,20,30,40,50,100], {prompt: 'Select Min Price'}, {class: "custom-select form-control col-3 mx-auto", id: "inlineFormCustomSelect" %>
          <%= f.select :price_gt, [0,10,20,30,40,50,100], {prompt: 'Select Min Price'}, { value: '', class: 'form-control ml-5', placeholder: "Minimum  Price" } %>

        </div>
        <%#= f.text_field :price_lteq, class: "form-control col-3 mr-3", placeholder: "Maximum Price" %>
        <div class="col-1.5 ml-2 form-style">
          <%#= f.select :price_gteq, [0,10,20,30,40,50,100], {prompt: 'Select Min Price'}, {class: "custom-select form-control col-3 mx-auto", id: "inlineFormCustomSelect" %>
          <%= f.select :price_lteq, [0,10,20,30,40,50,100], {prompt: 'Select Max Price'}, { value: '', class: 'form-control', placeholder: "Maximum Price" } %>

        </div>
        <div class="col-1.5 ml-2 form-style">
        <%= f.select :category_cont, StaticData::Constants::DRESS_CATEGORIES, {prompt: 'Select Category'}, { value: '', class: 'form-control', placeholder: "Category" } %>
        </div>
        <%= f.text_field :name_cont, class: "form-control col-2  ml-2", placeholder: "Dress"  %>
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
        </div>



        <%#= form_with url: items_path, method: :get, local: true do |f| %>
          <!-- <div class='form-group btn btn-light dropdown-toggle user-profile ml-5 col-2 input justify-content-end" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"'> -->
            <%#= f.select :category, StaticData::Constants::DRESS_CATEGORIES, {prompt: 'Select Category'}, { value: '', class: 'form-control', onchange: 'this.form.submit();' } %>
          <!-- </div> -->
        <%# end %>

      <% end %>
    </form>
    <% end %>

  </div>
</div>




<div class="container mt-5">


      <% content_for :search do %>
      <div class="container sort form-style mt-1">
      <h6 style="display: inline"><p style="display: inline">Sort by:</p></h6><%= sort_link @search, :price, "Price" %>
      <%= sort_link @search, :created_at, "Posted on" %>
      <%= sort_link @search, :title, "Likes" %>
      </div>
      <% end %>

    <div class="row">

      <% @items.each do |item| %>
      <div class="col-lg 3 col-md-3 col-sm-12 col-xs-12">
        <div class="card mb-5">
          <%= link_to item_path(item) do %>
          <%= image_tag item.image_url , class: "card-img-top img-fluid"%>
          <% end %>
          <div class="card-block">
            <p class="card-text mt-1 ml-1"><%= item.name %></p>
            <p id="grey-out" class="text-h4 ml-1 mt-0"> $ <%= item.price %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>


  </div>

app/views/items/manage_items.html.erb
<div class="container">
<p id="notice"><%= notice %></p>


<div class="row">

  <% @my_items.each do |item| %>
  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="card mb-5 mt-5">
      <%= link_to item_path(item) do %>
      <%= image_tag item.image_url , class: "card-img-top img-fluid"%>
      <% end %>

      <div class="card-block">
        <p class="text-h4"><%= item.name %></p>
        <p class="text-h4 text-primary"> $ <%= item.price %></p>
      </div>
      <% if user_signed_in? && item.user_id == current_user.id %>
      <div class="btn-group">
        <div class="btn btn-info back-button mr-1">
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
        </div>
        <div class="btn btn-info back-button ml-1">
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </div>
      </div>

        <% end %>
    </div>
  </div>
  <% end %>
</div>

<div class="btn btn-info back-button ml-1">
  <%= link_to 'Back', items_path %>
</div>
</div>

app/views/items/new.html.erb
<%= render 'form', item: @item %>
<div class="btn btn-info back-button">
  <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
</div>
<div class="row justify-content-around">
    <div class="col-lg-5 col-md-4 col-sm-12 col-xs-12">
      <div class="item-details">
        <div class="item-name">
          <%= @item.name %><br>
        </div>
        <%= @item.description %><br>
        SIZE M ><br>
        <%= @item.price %> to rent,  <p id="strikethrough">$150 </p>retail
      </div>
      <% posted_by_user = Profile.find_by_id(@item.user_id) %>

      <p id="grey-out">Posted on <%= @item.created_at.strftime("%d-%B") %> by
      <%= link_to posted_by_user.first_name, profile_path(@item.user_id), class: 'text-info' %></p>

      <% if current_user != NIL %>
        <% if @item.user_id == current_user.id %>

        <% else %>
          <%= link_to 'Contact Owner', messages_path, style: 'color: #008798' %>
        <% end %>
      <% end %>

      <% if current_user == NIL %>
        <%= link_to 'Contact Owner', messages_path %>
      <% end %>

      <div class="col-md-4">
      				<!-- Reservation form -->
      	<%= render 'bookings/form' %>
      </div>

      <br>


      <div class="mb-4">
        <h3 id="grey-out">Reviews</h3>
      </div>
        <% @reviews.each do |review| %>


            <img src="<%= review.user.profile.image_url %>" class='img-circle' width="70" height="70">
            <%= review.user.profile.first_name %>
            <p id="grey-out"><%= review.created_at.strftime("%d-%B") %></p>
            <td><%= review.content %></td>
          <br>
          <hr>
          <%#= link_to 'x', items_review_path,method: :delete%><br>


        <% end %>
        <div class="row">
          <%= render 'reviews/form' %>
        </div>

    </div>
    <div class="col-lg-5 col-md-7 col-sm-12 col-xs-12">
      <img src="<%= @item.image_url %>" class="img-fluid br-0">
      <p><%= form_with(model: @item, method: :patch) do |f| %>
        <% liked = @item.liked_by?(current_user) %>
        <%= f.hidden_field :liked, value: liked %>
        <%#= f.button liked ? 'Unlike' : 'Like' %>
        <%= f.button liked ? fa_icon("heart") : fa_icon("heart-o") %>
        <%#= f.button liked ? :type => :image :src => image_path("logo.png") : :type => :image :src => image_path("logo.png")%>
      <% end %></p>


       <% @users = User.where(id: [@item.likers.ids]) %>

      <% if @users != NIL %>
      Loved by
        <% @users.each do |user| %>
           <%= user.profile.first_name %>,
        <% end %>
      <% end %>
      <br>
      <div class="row justify-content-end">
        <div class="col-lg-3 col-md-2 col-sm-4 col-xs-4 ">
          <% if user_signed_in? && @item.user_id == current_user.id %>
            <%= link_to 'Edit', edit_item_path(@item) %> |
          <% end %>
          <%= link_to 'Back', items_path %>
        </div>
      </div>
    </div>
  </div>

app/views/items/show_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 mt-5">
      <ul id="conversations-list">
        <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
        <% end %>
      </ul>
    </div>

    <div class="col-md-3">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 id="grey-out" class="panel-title mt-5">Contacts</h3>
        </div>
        <div class="panel-body">
          <ul>
            <% @users.each do |user| %>
            <% profile = Profile.where(user_id: user.id) %>
            <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
            <br>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>