config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :reviews
  resources :items do
    resources :reviews
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# get '/' => 'items#index'
  root :to => 'home#index'
  get 'items/new' => 'items#new'
  get 'messages' => 'items#show_messages'
  get 'manage_items' => 'items#manage_items'


  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

   resources :items do
    resources :bookings, only: [:create, :show, :update, :edit]
   end

   resources :charges

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DressMarketplace</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
  <header>

    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-inverse">
        <a href="">
          <%= link_to(image_tag("dresso.png", height: '60', width: '60'), root_path) %>
        </a>
        <p class="logo">DRESSO</p>
        <!-- <div class="collapse navbar-collapse navbar-expand-lg navbar-inverse" id="navbarNav5"> -->

          <ul class="navbar-nav justify-content-end ml-auto navbar-expand-lg navbar-inverse">
            <li class="nav-item menu-item">
              <%= render 'devise/login_items' %>
            </li>
            <li class="nav-item menu-item">
              <%= render 'devise/registration_items' %>
            </li>
            <li class="nav-item menu-item navbar-expand-lg navbar-inverse">
              <% if user_signed_in? %>

              <div class="dropdown navbar-expand-lg navbar-inverse">

                <button class="btn dropdown-toggle fa fa-user ml-2 button-white navbar-expand-lg navbar-inverse" type="button" data-toggle="dropdown">
                <span class="caret"></span></button>
                <ul class="dropdown-menu navbar-expand-lg navbar-inverse">
                  <%= link_to('Home', items_path, :class => "nav-link")  %>
                  <%= link_to('Post a dress', new_item_path, :class => "nav-link")  %>
                  <%= link_to('Manage Listing', manage_items_path, :class => "nav-link dropdown-item")  %>
                  <%= link_to('Messages', messages_path, :class => "nav-link")  %>
                  <%#= link_to('Rental History', edit_user_registration_path, :class => "nav-link")  %>
                  <% if current_user.profile.present? %>
                  <%= link_to('My Profile', profile_path(current_user.id), :class => "nav-link")  %>
                  <% else %>
                  <%= link_to('My Profile', new_profile_path(current_user.id), :class => "nav-link")  %>
                  <% end %>
                  <%= link_to('Sign Out', destroy_user_session_path, method: :delete, :class => "nav-link")  %>
                </ul>
              </div>
              <% end %>
            </li>
          </ul>

        <!-- </div> -->
      </nav>


    </div>


  </header>
  <%= yield(:search) %>
  <%= yield %>
  <%= render :partial => "partials/footer" %>


</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>